name: coverage
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    name: Report Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          go mod download

      - name: Run tests with coverage output
        run: |
          go test -race -covermode atomic -coverprofile=covprofile ./...

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github

