name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      # For whatever reason, 1.21.9 blows up because it can't
      # find 'max' in some go lib... pinning to 1.21.4 fixes this
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint
        run: make lint

